export const categoriesTypes = {
  FETCH_CATEGORIES_STARTS: "FETCH_CATEGORIES_STARTS",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "FETCH_CATEGORIES_FAILED",
  ADD_CATEGORY_STARTS: "ADD_CATEGORY_STARTS",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILED: "ADD_CATEGORY_FAILED",
};
